class Cat < Volt::Model

  NAMES = [
    'Afro',
    'Archibald',
    'Babe',
    'Bacon',
    'Banjo',
    'Barney',
    'Big Guy',
    'Big Red',
    'Biggie Smalls',
    'Bilbo',
    'Billy the Kid',
    'Bimmer',
    'Bingo',
    'Biscuit',
    'Blue',
    'Bobby',
    'Bond',
    'Bones',
    'Boss',
    'Brain',
    'Brownie',
    'Bubba',
    'Buckaroo',
    'Buffalo Bill',
    'Burger',
    'Buster',
    'Byte',
    'Caesar',
    'Chewie',
    'Chubby',
    'Chuck Norris',
    'Churchill',
    'Clark Griswold',
    'Clark Kent',
    'Cletus',
    'Clumsy',
    'Cookie Monster',
    'Copernicus',
    'Crookshanks',
    'Cyrano',
    'Deputy Dawg',
    'Dickens',
    'Dilbert',
    'Donald Trump',
    'Doonesbury',
    'Dude',
    'Dynamite',
    'ET',
    'Einstein',
    'Elf',
    'Elmo',
    'Emo',
    'Ewok',
    'Fabio',
    'Farley',
    'Fuzzy',
    'Garfield',
    'Goliath',
    'Gonzo',
    'Gordo',
    'Grumpy Cat',
    'Hamlet',
    'Hansel',
    'Harry',
    'Heathcliff',
    'Hobbit',
    'Homer',
    'Jasper',
    'Jeckyll',
    'Jerry Lee',
    'Kerouac',
    'Killer',
    'Lancelot',
    'Macbeth',
    'Macgyver',
    'Marky Mark',
    'Monet',
    'Mr Bigglesworth',
    'Mr Jinx',
    'Mulligan',
    'Ninja',
    'OJ',
    'Ole',
    'Oreo',
    'Peanut Butter',
    'Pee Wee',
    'Picasso',
    'Pistol',
    'Porkchop',
    'Puck',
    'Puss in Boots',
    'Quixote',
    'Ricky Bobby',
    'Rogue',
    'Sable',
    'Sailor',
    'Scat Cat',
    'Seuss',
    'Sir Barks Alot',
    'Sockington',
    'Spud',
    'Squirt',
    'Stewie',
    'Sven',
    'TBone',
    'Taco',
    'Tiger',
    'Tigger',
    'Underdog',
    'Waffles',
    'Wagner',
    'Waldo',
    'Whiskers',
    'Yoda'
  ]

  def self.create_cats(store, city_id)
  	rand(10).times do
      store._cats << {name: NAMES.sample, city_id: city_id}
    end
  end

  def get_sum
    self._name.gsub(' ','').chars.map(&:my_ord).inject(:+)
  end

end

class String
  def my_ord
    self.downcase.ord - 96
  end
end